services:
  pythonapp:
    build: ./python/
    command: sh -c "sleep 10s ; python3 ./hello_world.py"
    depends_on:
      - proxysql

  mysql:
    build: ./mysql/
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'

  proxysql:
    build: ./proxysql/
    image: proxysql/proxysql
    restart: always
    container_name: proxysql
    command: tail -F anything
    volumes:
      - ./proxysql/proxysql.cnf:/etc/proxysql.cnf
    ports:
      - '6032:6032'
    depends_on:
      - mysql
